### ISSUE TITLE
Символьное значение в числовых textbox'aх

### ISSUE THREAD

**Issue by Rsengo** [sony65/Present#2]
![image](https://user-images.githubusercontent.com/26200531/39940137-7f54d9d6-5582-11e8-9197-52d41ddf6542.png)
![image](https://user-images.githubusercontent.com/26200531/39940146-87681e6c-5582-11e8-95f6-0ae2317da4e5.png)
При вводе символьных значений в поле для числового значения выбрасывется исключение

**Comment by sony65** [comment]
Исправлено
